using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Modal
{
    public class Consulta
    {
        public datos resulta(int para)
        {
            datos res = new datos();
            if (para == 1)
            {
                res.id = 1;
                res.nombre = "Marcelo";
            }
            else
            {
                res.id = 2;
                res.nombre = "Rodrigo";
            }


            //var consult = new [{ "BENEFICIO":"14019033300","FECHAEMISION":"43497","FECHALIQUIDACION":"43497","CONCEPTO":"1","EMPRESA":"1","IMPORTELIQUIDADO":"3812.51","IMPORTEDEUDATOTAL":"NULL","CANTIDADCUOTAS":"NULL","DESCRIPCONCEPTO":"P.B.U - PRESTACION BASICA UNIVERSAL","MARCADEBCRED":"C","CODIGOTIPOLIQ":"1","DESCTLIQ":"MENSUAL NORMAL","ESTADO":"9999","DESCRESTADO":"LIQUIDACION NORMAL"}];
            //               new { "BENEFICIO":"14019033300","FECHAEMISION":"43497","FECHALIQUIDACION":"43497","CONCEPTO":"1","EMPRESA":"2","IMPORTELIQUIDADO":"3141.07","IMPORTEDEUDATOTAL":"NULL","CANTIDADCUOTAS":"NULL","DESCRIPCONCEPTO":"P.C   - PRESTACION COMPENSATORIA","MARCADEBCRED":"C","CODIGOTIPOLIQ":"1","DESCTLIQ":"MENSUAL NORMAL","ESTADO":"9999","DESCRESTADO":"LIQUIDACION NORMAL"},
            //                { "BENEFICIO":"14019033300","FECHAEMISION":"43497","FECHALIQUIDACION":"43497","CONCEPTO":"1","EMPRESA":"3","IMPORTELIQUIDADO":"284.86","IMPORTEDEUDATOTAL":"NULL","CANTIDADCUOTAS":"NULL","DESCRIPCONCEPTO":"P.A.P - PRESTACION ADIC.P/PERMANENC","MARCADEBCRED":"C","CODIGOTIPOLIQ":"1","DESCTLIQ":"MENSUAL NORMAL","ESTADO":"9999","DESCRESTADO":"LIQUIDACION NORMAL"},
            //                { "BENEFICIO":"14019033300","FECHAEMISION":"43497","FECHALIQUIDACION":"43497","CONCEPTO":"2","EMPRESA":"1","IMPORTELIQUIDADO":"5764.22","IMPORTEDEUDATOTAL":"NULL","CANTIDADCUOTAS":"NULL","DESCRIPCONCEPTO":"PRESTACION ANUAL COMPLEMENTARIA","MARCADEBCRED":"C","CODIGOTIPOLIQ":"1","DESCTLIQ":"MENSUAL NORMAL","ESTADO":"9999","DESCRESTADO":"LIQUIDACION NORMAL"},
            //                { "BENEFICIO":"14019033300","FECHAEMISION":"43497","FECHALIQUIDACION":"43497","CONCEPTO":"88","EMPRESA":"0","IMPORTELIQUIDADO":"4290","IMPORTEDEUDATOTAL":"NULL","CANTIDADCUOTAS":"NULL","DESCRIPCONCEPTO":"COMPLEMENTO AL MINIMO-DECRETO 525/9","MARCADEBCRED":"C","CODIGOTIPOLIQ":"1","DESCTLIQ":"MENSUAL NORMAL","ESTADO":"9999","DESCRESTADO":"LIQUIDACION NORMAL"},
            //                { "BENEFICIO":"14019033300","FECHAEMISION":"43497","FECHALIQUIDACION":"43497","CONCEPTO":"318","EMPRESA":"8","IMPORTELIQUIDADO":"345.85","IMPORTEDEUDATOTAL":"NULL","CANTIDADCUOTAS":"NULL","DESCRIPCONCEPTO":"OBRA SOCIAL 3% SOBRE HABERES","MARCADEBCRED":"D","CODIGOTIPOLIQ":"1","DESCTLIQ":"MENSUAL NORMAL","ESTADO":"9999","DESCRESTADO":"LIQUIDACION NORMAL"},
            //                { "BENEFICIO":"14019033300","FECHAEMISION":"43497","FECHALIQUIDACION":"43497","CONCEPTO":"319","EMPRESA":"11","IMPORTELIQUIDADO":"172.93","IMPORTEDEUDATOTAL":"NULL","CANTIDADCUOTAS":"NULL","DESCRIPCONCEPTO":"DESCUENTO PRESTACION ANUAL COMPLEME","MARCADEBCRED":"D","CODIGOTIPOLIQ":"1","DESCTLIQ":"MENSUAL NORMAL","ESTADO":"9999","DESCRESTADO":"LIQUIDACION NORMAL"},
            //                { "BENEFICIO":"14019033300","FECHAEMISION":"43525","FECHALIQUIDACION":"43525","CONCEPTO":"1","EMPRESA":"1","IMPORTELIQUIDADO":"25","IMPORTEDEUDATOTAL":"NULL","CANTIDADCUOTAS":"NULL","DESCRIPCONCEPTO":"P.B.U - PRESTACION BASICA UNIVERSAL","MARCADEBCRED":"C","CODIGOTIPOLIQ":"1","DESCTLIQ":"MENSUAL NORMAL","ESTADO":"9999","DESCRESTADO":"LIQUIDACION NORMAL"},
            //                { "BENEFICIO":"14019033300","FECHAEMISION":"43525","FECHALIQUIDACION":"43525","CONCEPTO":"1","EMPRESA":"1","IMPORTELIQUIDADO":"25","IMPORTEDEUDATOTAL":"NULL","CANTIDADCUOTAS":"NULL","DESCRIPCONCEPTO":"P.B.U - PRESTACION BASICA UNIVERSAL","MARCADEBCRED":"C","CODIGOTIPOLIQ":"2","DESCTLIQ":"COMPLEMENTARIA 1","ESTADO":"9999","DESCRESTADO":"LIQUIDACION NORMAL"}
        

            return res;
        }



        public class datos
        {
            public int id { get; set; }
            public string nombre { get; set; }
        }

    }

    
}